config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"

  resources :recipes 
  resources :ingredients

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  has_and_belongs_to_many :recipes

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  has_and_belongs_to_many :ingredients

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  
  def index
    @ingredients = Ingredient.all

    render json: @ingredients
  end

  def new
    @ingredient = Ingredient.new
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    
    if @ingredient.save()
      redirect_to @ingredient
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save()
      redirect_to @recipe
    else 
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def recipe_params
      params.require(:recipe).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.erb
<%= form_with model: ingredient do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% ingredient.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>

  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/index.html.erb
<h1>All ingredients</h1>


<ul>
  <% @ingredients.each do |ingredient| %>
    <li>
      <%= link_to ingredient.name, ingredient%>
    </li>
  <% end %>
</ul>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render "form", ingredient: @ingredient %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>

<h2>Recipes that use this ingredient:</h2>
<% @ingredient.recipes.each do |recipes| %>
  <p>
    <%= recipes.title %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with model: recipe do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% recipe.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% recipe.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <% Ingredient.where(id: 0..20).each do |ingredient| %>
    <p> <%= ingredient.name %> </p>
  <% end %>


    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1> Edit Recipe </h1>

<%= render "form", recipe: @recipe %>

app/views/recipes/index.html.erb
<h1>Recipe List</h1>

<ul>
  <% @recipes.each do |recipe| %>
    <li>
      <%= link_to recipe.title, recipe%>
    </li>
  <% end %>
</ul>

<p><%= link_to "Check the ingredients list", "ingredients" %></p>

<p><%= link_to "Add new recipe", new_recipe_path(@recipe) %></p>
<p><%= link_to "Add new ingredient", new_ingredient_path(@ingredient) %></p>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render "form", recipe: @recipe %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>

<p><%= @recipe.description %></p>

<ul>
  <li><%= link_to "Edit", edit_recipe_path(@recipe) %></li>
  <li><%= link_to "Destroy", recipe_path(@recipe), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Ingredients:</h2>
<% @recipe.ingredients.each do |ingredient| %>
  <p>
    <%= ingredient.name %>
  </p>
<% end %>

<p><%= link_to "Back to recipes", root_path %></p>